export * from "./NFTCard";
export * from "./Collections";
export * from "./Contact";
export * from "./Footer";
export * from "./Header";
export * from "./Landing";
export * from "./Drops";
export * from "./Categories";
export * from "./CNav";
export * from "./Settings";
export * from "./DropdownComp";
export * from "./AdminProfile";
export * from "./Create";
export * from "./NotFound";
export * from "./Wrapper";
export * from "./Home";
// export * from "./Customer";
export * from "./User";
export * from "./NFTDetail";
export * from "./UserDetail";
// export * from './Sidebar';
